[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "polyA"
author = "Kaitlin Carey"
author-email = "kaitlin1.carey@umontana.edu"
home-page = "https://github.com/TravisWheelerLab/polyA"
classifiers = ["License :: OSI Approved :: BSD License"]
description-file = "README.md"

[tool.flit.sdist]
exclude = [
    "fixtures/",
    "supporting_materials/",
    "tests/",
    "test_inputs/",
]
